### ISSUE TITLE
how use inspector-gadget analysis weblogic jars

### ISSUE THREAD

**Issue by hktalent** [frohoff/inspector-gadget#2]
how use inspector-gadget analysis weblogic jars
thanks
eg:
load weblogic/*.jar

**Comment by fnmsd** [comment]
src/main/scala/org/frohoff/inspectorgadget/IndexApp.scala
copy line 115-118 and modify for weblogic directory.
It will have a huge memory usage.

**Comment by hktalent** [comment]
thks @fnmsd

**Comment by hktalent** [comment]
@fnmsd 加你微信了，交流下哇？
